const SETTINGS_MODAL = {
	TITLE: 'sm_title',
	ARIA: 'sm_aria',
	PRACTICE_LABEL: 'sm_practice_label',
	PRACTICE_TEST_ID: 'practice_selector',
	PRACTICE_ARIA: 'sm_practice_aria',
	PRACTICE_OPTIONS: [
		{ key: 'sm_reference_option', value: 'REFERENCE' },
		{ key: 'sm_structure_option', value: 'STRUCTURE' },
		{ key: 'sm_mirror_option', value: 'MIRROR' },
		{ key: 'sm_strategic_option', value: 'STRATEGIC' },
	],
	TIMER_LABEL: 'sm_timer_label',
	TIMER_TEST_ID: 'timer_selector',
	TIMER_ARIA: 'sm_timer_aria',
	TIMER_OPTIONS: [
		{ key: 'sm_segs_option', value: 30 },
		{ key: 'sm_min_option', value: 60 },
		{ key: 'sm_mins_option', value: 180 },
		{ key: 'sm_mins_option', value: 300 },
		{ key: 'sm_mins_option', value: 600 },
		{ key: 'sm_mins_option', value: 1800 },
		{ key: 'sm_mins_option', value: 3600 },
		{ key: 'sm_free_option', value: 0 },
	],
	REFERENCES_EMPTY_LABEL: 'sm_references_empty_label',
	REFERENCES_DATA_LABEL: 'sm_references_data_label',
	REFERENCES_TEST_ID: 'references_loader',
	REFERENCES_ARIA: 'sm_references_aria',
	RANDOM_LABEL: 'sm_random_label',
	RANDOM_TEST_ID: 'random_checkbox',
	RANDOM_ARIA: 'sm_random_aria',
	BTN_TEXT: 'sm_btn_text',
	BTN_TEST_ID: 'settings_start_btn',
	BTN_ARIA: 'sm_btn_aria',
	TOAST_TITLE: 'sm_toast_title',
	TOAST_DESCRIPTION: 'sm_toast_description',
};

export default SETTINGS_MODAL;
