import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
	Box,
	Button,
	Flex,
	Modal,
	ModalContent,
	ModalFooter,
	ModalHeader,
	ModalOverlay,
} from '@chakra-ui/react';

import { Settings } from '@utils/constants';
import {
	ReferencesCanvas,
	SettingsModal,
	CustomizeModal,
	AboutModal,
} from '@components/home';
import useToggle from '@hooks/useToggle';

/**
 *
 * TODOs:
 * FooterControls onFinishCall (Pending)
 * ReferencesCanvas fit reference on div (Pending)
 * Responsive Design (Pending)
 * Custom theme colors & light/dark modes (Pending)
 * Localization en/sp (Pending)
 *
 **/

const HomePage: NextPage = () => {
	const [settings, setSettings] = useState<Settings>();
	const [current, setCurrent] = useState<number>(0);
	const { value: showSettings, onToggle: onToggleSettings } = useToggle();
	const { value: showCustomize, onToggle: onToggleCustomize } = useToggle();
	const { value: showAbout, onToggle: onToggleAbout } = useToggle(true);

	const onPrevRef = () => {
		if (current > 0) {
			setCurrent(current - 1);
		}
	};

	const onNextRef = () => {
		if (settings && current < settings.imgs.length) {
			setCurrent(current + 1);
		}
	};

	return (
		<>
			<Head>
				<title>Doodleline | Practice</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* <Flex direction='row' h='100vh' w='100vw'>
				<Box flex={1} p={5} h='100%' w='100%'>
					<SideSettings
						onStart={(settings) => setSettings(settings)}
						onOpenHelp={() => console.log('Help')}
						onOpenCustomize={() => console.log('Customize')}
					/>
				</Box>
				<Box flex={2} p={5} h='100%' w='100%'>
					<ReferencesCanvas imgs={settings?.imgs} current={current} />
				</Box>
			</Flex> */}
			<SettingsModal
				isOpen={showSettings}
				onClose={onToggleSettings}
				onStart={(settings) => setSettings(settings)}
			/>
			<CustomizeModal isOpen={showCustomize} onClose={onToggleCustomize} />
			<AboutModal isOpen={showAbout} onClose={onToggleAbout} />
		</>
	);
};

export default HomePage;
