import styles from '@sass/Home.module.scss';
import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

// import PracticeModal from 'src/layout/home/PracticeModal/PracticeModal';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Doodleline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</>
	);
};

export default Home;
